apiVersion: v1
kind: Service
metadata:
  name: orchestrator-api
  labels:
    run: exatauser
spec:
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: NodePort
  selector:
    run: orchestrator-api

apiVersion: app/v1
kind: Deployment
metadata:
  name: orchestrator-api
spec:
  replicas: 2
  template: 
    metadata:
      labels:
        run: orchestrator-api
    spec:
      containers:
      - name: orchestrator-api
        image: us.icr.io/iux-miaspace1/orchestrator-api
        ports:
        - containerPort: 8084